camunda.bpm:
  application:
     isDeleteUponUndeploy: false
     isScanForProcessDefinitions: false
     isDeployChangedOnly: true
     isResumePreviousVersions: true
     resumePreviousBy: a value

#camunda.bpm.auto-deployment-enabled: false

server:
  port: 9080
#management:
#  port: 9081